import argparse
import subprocess
import sys
import uuid
from pathlib import Path
import xml.etree.ElementTree as ET


def read_csproj_metadata(csproj_path: Path) -> dict:
    tree = ET.parse(csproj_path)
    root = tree.getroot()

    def find_text(tag: str, default: str = "") -> str:
        for elem in root.iter():
            if elem.tag.endswith(tag) and elem.text:
                return elem.text.strip()
        return default

    return {
        "app_name": find_text("Product", "Dual AutoClicker"),
        "assembly_name": find_text("AssemblyName", "DualAutoClicker"),
        "version": find_text("Version", "1.0.0"),
        "publisher": find_text("Company", "Unknown"),
        "icon": find_text("ApplicationIcon", ""),
    }


def resolve_iscc() -> str:
    candidates = [
        r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        r"C:\Program Files\Inno Setup 6\ISCC.exe",
    ]
    for path in candidates:
        if Path(path).exists():
            return path
    return "ISCC.exe"


def build_iss_content(metadata: dict, app_id: str, publish_dir: Path) -> str:
    app_name = metadata["app_name"]
    exe_name = f"{metadata['assembly_name']}.exe"
    version = metadata["version"]
    publisher = metadata["publisher"]
    icon = metadata["icon"] or "Assets\\icon.ico"

    return f"""; Inno Setup script for {app_name}
; Generated by build_installer.py

#define MyAppName \"{app_name}\"
#define MyAppExeName \"{exe_name}\"
#define MyAppVersion \"{version}\"
#define MyAppPublisher \"{publisher}\"
#define MyAppURL \"https://github.com/\"

[Setup]
AppId={{{{{app_id}}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
DisableProgramGroupPage=yes
OutputBaseFilename=DualAutoClicker-Setup
Compression=lzma2
SolidCompression=yes
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
SetupIconFile={icon}
UninstallDisplayIcon={{app}}\\{{#MyAppExeName}}

[Languages]
Name: \"turkish\"; MessagesFile: \"compiler:Languages\\Turkish.isl\"
Name: \"english\"; MessagesFile: \"compiler:Default.isl\"

[Tasks]
Name: \"desktopicon\"; Description: \"Masaüstü kısayolu oluştur\"; GroupDescription: \"Ek görevler\"; Flags: unchecked

[Files]
Source: \"{publish_dir.as_posix().replace('/', '\\')}\\*\"; DestDir: \"{{app}}\"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: \"{{group}}\\{{#MyAppName}}\"; Filename: \"{{app}}\\{{#MyAppExeName}}\"
Name: \"{{autodesktop}}\\{{#MyAppName}}\"; Filename: \"{{app}}\\{{#MyAppExeName}}\"; Tasks: desktopicon

[Run]
Filename: \"{{app}}\\{{#MyAppExeName}}\"; Description: \"{{cm:LaunchProgram,{{#MyAppName}}}}\"; Flags: nowait postinstall skipifsilent
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Inno Setup installer for DualAutoClicker")
    parser.add_argument("--csproj", default="DualAutoClicker.csproj")
    parser.add_argument("--configuration", default="Release")
    parser.add_argument("--runtime", default="win-x64")
    parser.add_argument("--self-contained", default="true")
    parser.add_argument("--app-id", default="")
    parser.add_argument("--skip-publish", action="store_true")
    parser.add_argument("--skip-installer", action="store_true")
    args = parser.parse_args()

    repo_root = Path.cwd()
    csproj_path = repo_root / args.csproj
    if not csproj_path.exists():
        print(f"csproj bulunamadi: {csproj_path}")
        return 1

    metadata = read_csproj_metadata(csproj_path)
    publish_dir = repo_root / "bin" / args.configuration / "net8.0-windows10.0.19041.0" / args.runtime / "publish"

    if not args.skip_publish:
        publish_cmd = [
            "dotnet",
            "publish",
            "-c",
            args.configuration,
            "-r",
            args.runtime,
            "--self-contained",
            args.self_contained,
        ]
        print("Publish komutu:", " ".join(publish_cmd))
        subprocess.check_call(publish_cmd)

    app_id = args.app_id or str(uuid.uuid4())
    iss_path = repo_root / "installer.iss"
    iss_content = build_iss_content(metadata, app_id, publish_dir)
    iss_path.write_text(iss_content, encoding="utf-8")
    print(f"ISS olusturuldu: {iss_path}")

    if not args.skip_installer:
        iscc = resolve_iscc()
        print(f"ISCC: {iscc}")
        subprocess.check_call([iscc, str(iss_path)])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
